;;; usgc-jetbrains-theme.el --- USGC JetBrains theme -*- lexical-binding: t; -*-

;;; Code:

(deftheme usgc-jetbrains)

(defgroup usgc-jetbrains nil
  "JetBrains-derived USGC theme options."
  :group 'faces)

(defcustom usgc-jetbrains-enlarge-headings t
  "Use different font sizes for some headings and titles."
  :type 'boolean
  :group 'usgc-jetbrains)

(defcustom usgc-jetbrains-height-title-1 1.3
  "Font size 130%."
  :type 'number
  :group 'usgc-jetbrains)

(defcustom usgc-jetbrains-height-title-2 1.1
  "Font size 110%."
  :type 'number
  :group 'usgc-jetbrains)

(defcustom usgc-jetbrains-height-title-3 1.0
  "Font size 100%."
  :type 'number
  :group 'usgc-jetbrains)

(defcustom usgc-jetbrains-height-doc-title 1.25
  "Font size 125%."
  :type 'number
  :group 'usgc-jetbrains)

(defcustom usgc-jetbrains-bolder-keywords t
  "Use bold weight for syntax faces."
  :type 'boolean
  :group 'usgc-jetbrains)

(let ((colors '((jetbrains-bg "#0E0E0E" "#0E0E0E" "#0E0E0E")
                (jetbrains-fg "#9B9B9B" "#9B9B9B" "#9B9B9B")
                (jetbrains-current "#00083C" "#00083C" "#00083C")
                (jetbrains-region "#005739" "#005739" "#005739")
                (jetbrains-comment "#5C6370" "#5C6370" "#5C6370")
                (jetbrains-comment-alt "#444A53" "#444A53" "#444A53")
                (jetbrains-cyan "#02C4BA" "#02C4BA" "#02C4BA")
                (jetbrains-green "#89CA78" "#89CA78" "#89CA78")
                (jetbrains-orange "#FF8100" "#FF8100" "#FF8100")
                (jetbrains-pink "#FD5DD1" "#FD5DD1" "#FD5DD1")
                (jetbrains-purple "#9273FD" "#9273FD" "#9273FD")
                (jetbrains-red "#FD4646" "#FD4646" "#FD4646")
                (jetbrains-yellow "#DBB500" "#DBB500" "#DBB500")
                (jetbrains-blue "#61AFEF" "#61AFEF" "#61AFEF")
                (jetbrains-link "#2E86FF" "#2E86FF" "#2E86FF")
                (jetbrains-gold "#E5C07B" "#E5C07B" "#E5C07B")
                (jetbrains-teal "#2EA1FF" "#2EA1FF" "#2EA1FF")
                (jetbrains-maroon "#583535" "#583535" "#583535")
                (jetbrains-gray "#494F59" "#494F59" "#494F59")
                (jetbrains-success "#46B268" "#46B268" "#46B268")
                (jetbrains-warning "#F44747" "#F44747" "#F44747"))))
  (let ((faces
         '((cursor :background ,jetbrains-fg)
           (default :background ,jetbrains-bg :foreground ,jetbrains-fg)
           (error :foreground ,jetbrains-red :weight bold)
           (warning :foreground ,jetbrains-orange)
           (success :foreground ,jetbrains-success)
           (fringe :background ,jetbrains-bg :foreground ,jetbrains-gray)
           (header-line :background ,jetbrains-current :foreground ,jetbrains-fg :box nil)
           (highlight :background ,jetbrains-current :foreground ,jetbrains-fg)
           (hl-line :background "#2B2B2B" :extend t)
           (link :foreground ,jetbrains-link :underline t)
           (line-number :background ,jetbrains-bg :foreground ,jetbrains-gray)
           (line-number-current-line :background ,jetbrains-bg :foreground ,jetbrains-fg)
           (minibuffer-prompt :foreground ,jetbrains-pink :weight bold)
           (mode-line :background "#1F1F1F" :foreground ,jetbrains-fg :box nil)
           (mode-line-inactive :background ,jetbrains-bg :foreground ,jetbrains-comment :box nil)
           (region :background ,jetbrains-region :foreground ,jetbrains-fg :extend t)
           (shadow :foreground ,jetbrains-comment)
           (show-paren-match :foreground ,jetbrains-green :weight bold)
           (show-paren-mismatch :background ,jetbrains-maroon :foreground ,jetbrains-red :weight bold)
           (tooltip :background ,jetbrains-current :foreground ,jetbrains-fg)
           (vertical-border :foreground ,jetbrains-comment-alt)
           (match :background ,jetbrains-green :foreground ,jetbrains-bg :weight bold)
           (lazy-highlight :background ,jetbrains-comment-alt :foreground ,jetbrains-gold)
           (isearch :inherit match)
           (isearch-fail :background ,jetbrains-red :foreground ,jetbrains-bg)
           (trailing-whitespace :background ,jetbrains-warning)
           (font-lock-builtin-face :foreground ,jetbrains-blue)
           (font-lock-comment-face :foreground ,jetbrains-comment)
           (font-lock-comment-delimiter-face :foreground ,jetbrains-comment)
           (font-lock-constant-face :foreground ,jetbrains-gold)
           (font-lock-doc-face :foreground ,jetbrains-comment-alt)
           (font-lock-doc-markup-face :foreground ,jetbrains-comment-alt)
           (font-lock-function-name-face :foreground ,jetbrains-purple
                                         ,@(when usgc-jetbrains-bolder-keywords
                                             (list :weight 'bold)))
           (font-lock-function-call-face :foreground ,jetbrains-blue)
           (font-lock-keyword-face :foreground ,jetbrains-pink
                                   ,@(when usgc-jetbrains-bolder-keywords
                                       (list :weight 'bold)))
           (font-lock-negation-char-face :foreground ,jetbrains-pink)
           (font-lock-number-face :foreground ,jetbrains-red)
           (font-lock-operator-face :foreground ,jetbrains-pink)
           (font-lock-bracket-face :foreground ,jetbrains-fg)
           (font-lock-delimiter-face :foreground ,jetbrains-fg)
           (font-lock-escape-face :foreground ,jetbrains-cyan)
           (font-lock-misc-punctuation-face :foreground ,jetbrains-fg)
           (font-lock-preprocessor-face :foreground ,jetbrains-orange)
           (font-lock-property-name-face :foreground ,jetbrains-teal)
           (font-lock-property-use-face :foreground ,jetbrains-teal)
           (font-lock-punctuation-face :foreground ,jetbrains-fg)
           (font-lock-regexp-grouping-backslash :foreground ,jetbrains-cyan)
           (font-lock-regexp-grouping-construct :foreground ,jetbrains-gold)
           (font-lock-string-face :foreground ,jetbrains-yellow)
           (font-lock-type-face :foreground ,jetbrains-success)
           (font-lock-variable-name-face :foreground ,jetbrains-teal)
           (font-lock-variable-use-face :foreground ,jetbrains-fg)
           (font-lock-warning-face :foreground ,jetbrains-red :weight bold)
           (ansi-color-black :foreground ,jetbrains-bg :background ,jetbrains-bg)
           (ansi-color-blue :foreground ,jetbrains-blue :background ,jetbrains-blue)
           (ansi-color-bright-blue :foreground ,jetbrains-link :background ,jetbrains-link)
           (ansi-color-cyan :foreground ,jetbrains-cyan :background ,jetbrains-cyan)
           (ansi-color-green :foreground ,jetbrains-green :background ,jetbrains-green)
           (ansi-color-magenta :foreground ,jetbrains-pink :background ,jetbrains-pink)
           (ansi-color-red :foreground ,jetbrains-red :background ,jetbrains-red)
           (ansi-color-white :foreground ,jetbrains-fg :background ,jetbrains-fg)
           (ansi-color-yellow :foreground ,jetbrains-yellow :background ,jetbrains-yellow)
           (company-tooltip :background ,jetbrains-current :foreground ,jetbrains-fg)
           (company-tooltip-selection :background ,jetbrains-region :foreground ,jetbrains-fg)
           (company-tooltip-common :foreground ,jetbrains-pink :weight bold)
           (company-tooltip-annotation :foreground ,jetbrains-cyan)
           (corfu-default :background ,jetbrains-current :foreground ,jetbrains-fg)
           (corfu-current :background ,jetbrains-region :foreground ,jetbrains-fg)
           (corfu-border :background ,jetbrains-comment-alt)
           (corfu-bar :background ,jetbrains-comment)
           (corfu-candidate-overlay-face :foreground ,jetbrains-comment)
           (corfu-quick1 :background ,jetbrains-green :foreground ,jetbrains-bg :weight bold)
           (corfu-quick2 :background ,jetbrains-pink :foreground ,jetbrains-bg :weight bold)
           (completions-common-part :foreground ,jetbrains-green)
           (completions-first-difference :foreground ,jetbrains-pink :weight bold)
           (consult-async-split :foreground ,jetbrains-red)
           (consult-file :foreground ,jetbrains-blue :weight bold)
           (consult-highlight-mark :inherit match)
           (consult-highlight-match :inherit match)
           (consult-imenu-prefix :foreground ,jetbrains-comment)
           (consult-key :foreground ,jetbrains-blue :weight bold)
           (consult-line-number :foreground ,jetbrains-comment)
           (consult-line-number-prefix :foreground ,jetbrains-comment)
           (consult-preview-insertion :background ,jetbrains-current)
           (diff-added :background ,jetbrains-green :foreground ,jetbrains-bg :extend t)
           (diff-removed :background ,jetbrains-maroon :foreground ,jetbrains-red :extend t)
           (diff-changed :background ,jetbrains-current :foreground ,jetbrains-gold :extend t)
           (diff-refine-added :background ,jetbrains-success :foreground ,jetbrains-bg)
           (diff-refine-removed :background ,jetbrains-red :foreground ,jetbrains-bg)
           (diff-indicator-added :foreground ,jetbrains-green)
           (diff-indicator-removed :foreground ,jetbrains-red)
           (diff-indicator-changed :foreground ,jetbrains-orange)
           (dired-directory :foreground ,jetbrains-blue :weight bold)
           (dired-flagged :foreground ,jetbrains-red)
           (dired-header :foreground ,jetbrains-pink :weight bold)
           (dired-ignored :foreground ,jetbrains-comment)
           (dired-marked :foreground ,jetbrains-orange :weight bold)
           (dired-symlink :foreground ,jetbrains-cyan :slant italic)
           (magit-branch-local :foreground ,jetbrains-blue)
           (magit-branch-remote :foreground ,jetbrains-green)
           (magit-diff-added :foreground ,jetbrains-green :background ,jetbrains-bg)
           (magit-diff-added-highlight :foreground ,jetbrains-green :background ,jetbrains-current)
           (magit-diff-removed :foreground ,jetbrains-red :background ,jetbrains-bg)
           (magit-diff-removed-highlight :foreground ,jetbrains-red :background ,jetbrains-current)
           (magit-section-heading :foreground ,jetbrains-pink :weight bold)
           (magit-section-highlight :background ,jetbrains-current :extend t)
           (eglot-highlight-symbol-face :background ,jetbrains-current)
           (eglot-mode-line :foreground ,jetbrains-green :weight bold)
           (eglot-diagnostic-tag-unnecessary-face :underline (:style wave :color ,jetbrains-orange))
           (lsp-details-face :foreground ,jetbrains-comment :height 0.9)
           (lsp-face-rename :inherit match)
           (lsp-headerline-breadcrumb-separator-face :foreground ,jetbrains-comment)
           (lsp-headerline-breadcrumb-path-face :foreground ,jetbrains-yellow)
           (lsp-headerline-breadcrumb-project-prefix-face :foreground ,jetbrains-blue :weight bold)
           (lsp-headerline-breadcrumb-symbols-face :foreground ,jetbrains-comment-alt :weight bold)
           (lsp-lens-mouse-face :background ,jetbrains-current :foreground ,jetbrains-link :underline t)
           (lsp-modeline-code-actions-face :foreground ,jetbrains-orange)
           (lsp-modeline-code-actions-preferred-face :foreground ,jetbrains-orange :weight bold)
           (lsp-signature-posframe :background ,jetbrains-current :foreground ,jetbrains-fg)
           (lsp-signature-highlight-function-argument :background ,jetbrains-current
                                                      :foreground ,jetbrains-green
                                                      :weight bold)
           (lsp-ui-doc-background :background ,jetbrains-current)
           (lsp-ui-doc-header :foreground ,jetbrains-bg :background ,jetbrains-cyan :weight bold)
           (org-block :foreground ,jetbrains-yellow)
           (org-code :foreground ,jetbrains-cyan)
           (org-date :foreground ,jetbrains-link :underline t)
           (org-document-title :foreground ,jetbrains-gold :weight bold
                               ,@(when usgc-jetbrains-enlarge-headings
                                   (list :height usgc-jetbrains-height-doc-title)))
           (org-done :foreground ,jetbrains-green)
           (org-level-1 :foreground ,jetbrains-pink :weight bold
                        ,@(when usgc-jetbrains-enlarge-headings
                            (list :height usgc-jetbrains-height-title-1)))
           (org-level-2 :foreground ,jetbrains-purple :weight bold
                        ,@(when usgc-jetbrains-enlarge-headings
                            (list :height usgc-jetbrains-height-title-2)))
           (org-level-3 :foreground ,jetbrains-green
                        ,@(when usgc-jetbrains-enlarge-headings
                            (list :height usgc-jetbrains-height-title-3)))
           (org-level-4 :foreground ,jetbrains-gold)
           (org-link :foreground ,jetbrains-link :underline t)
           (org-quote :foreground ,jetbrains-comment-alt :slant italic)
           (org-table :foreground ,jetbrains-teal)
           (org-todo :foreground ,jetbrains-orange :weight bold)
           (markdown-blockquote-face :foreground ,jetbrains-comment-alt :slant italic)
           (markdown-code-face :foreground ,jetbrains-yellow)
           (markdown-header-face-1 :foreground ,jetbrains-pink :weight bold
                                   ,@(when usgc-jetbrains-enlarge-headings
                                       (list :height usgc-jetbrains-height-title-1)))
           (markdown-header-face-2 :foreground ,jetbrains-purple :weight bold
                                   ,@(when usgc-jetbrains-enlarge-headings
                                       (list :height usgc-jetbrains-height-title-2)))
           (markdown-header-face-3 :foreground ,jetbrains-green
                                   ,@(when usgc-jetbrains-enlarge-headings
                                       (list :height usgc-jetbrains-height-title-3)))
           (markdown-inline-code-face :foreground ,jetbrains-cyan)
           (rainbow-delimiters-depth-1-face :foreground ,jetbrains-fg)
           (rainbow-delimiters-depth-2-face :foreground ,jetbrains-blue)
           (rainbow-delimiters-depth-3-face :foreground ,jetbrains-purple)
           (rainbow-delimiters-depth-4-face :foreground ,jetbrains-pink)
           (rainbow-delimiters-depth-5-face :foreground ,jetbrains-orange)
           (rainbow-delimiters-depth-6-face :foreground ,jetbrains-green)
           (rainbow-delimiters-depth-7-face :foreground ,jetbrains-yellow)
           (rainbow-delimiters-unmatched-face :foreground ,jetbrains-red :weight bold)
           (tab-bar :background ,jetbrains-current :foreground ,jetbrains-gold)
           (tab-bar-tab :background ,jetbrains-bg :foreground ,jetbrains-pink :box nil)
           (tab-bar-tab-inactive :background ,jetbrains-current :foreground ,jetbrains-comment :box nil)
           (tab-line :background ,jetbrains-current :foreground ,jetbrains-gold)
           (tab-line-tab-current :background ,jetbrains-bg :foreground ,jetbrains-pink :weight bold :box nil)
           (tab-line-tab :background ,jetbrains-current :foreground ,jetbrains-comment :box nil)
           (treesit-font-lock-attribute-face :foreground ,jetbrains-blue)
           (treesit-font-lock-bracket-face :foreground ,jetbrains-fg)
           (treesit-font-lock-builtin-face :foreground ,jetbrains-blue)
           (treesit-font-lock-comment-face :foreground ,jetbrains-comment)
           (treesit-font-lock-constant-face :foreground ,jetbrains-gold)
           (treesit-font-lock-constructor-face :foreground ,jetbrains-purple)
           (treesit-font-lock-delimiter-face :foreground ,jetbrains-fg)
           (treesit-font-lock-doc-face :foreground ,jetbrains-comment-alt)
           (treesit-font-lock-embedded-face :foreground ,jetbrains-cyan)
           (treesit-font-lock-escape-face :foreground ,jetbrains-cyan)
           (treesit-font-lock-function-face :foreground ,jetbrains-purple)
           (treesit-font-lock-keyword-face :foreground ,jetbrains-pink
                                           ,@(when usgc-jetbrains-bolder-keywords
                                               (list :weight 'bold)))
           (treesit-font-lock-label-face :foreground ,jetbrains-orange)
           (treesit-font-lock-number-face :foreground ,jetbrains-red)
           (treesit-font-lock-operator-face :foreground ,jetbrains-pink)
           (treesit-font-lock-property-face :foreground ,jetbrains-teal)
           (treesit-font-lock-punctuation-face :foreground ,jetbrains-fg)
           (treesit-font-lock-string-face :foreground ,jetbrains-yellow)
           (treesit-font-lock-type-face :foreground ,jetbrains-gold)
           (treesit-font-lock-variable-face :foreground ,jetbrains-teal)
           (tree-sitter-hl-face:attribute :inherit font-lock-constant-face)
           (tree-sitter-hl-face:comment :inherit font-lock-comment-face)
           (tree-sitter-hl-face:constant :inherit font-lock-constant-face)
           (tree-sitter-hl-face:escape :foreground ,jetbrains-cyan)
           (tree-sitter-hl-face:function :inherit font-lock-function-name-face)
           (tree-sitter-hl-face:function.call :foreground ,jetbrains-blue :weight normal)
           (tree-sitter-hl-face:keyword :inherit font-lock-keyword-face)
           (tree-sitter-hl-face:number :inherit font-lock-number-face)
           (tree-sitter-hl-face:operator :inherit font-lock-operator-face)
           (tree-sitter-hl-face:property :foreground ,jetbrains-teal)
           (tree-sitter-hl-face:punctuation :foreground ,jetbrains-fg)
           (tree-sitter-hl-face:string :inherit font-lock-string-face)
           (tree-sitter-hl-face:type :inherit font-lock-type-face)
           (tree-sitter-hl-face:type.parameter :foreground ,jetbrains-gold)
           (tree-sitter-hl-face:variable :inherit font-lock-variable-name-face)
           (tree-sitter-hl-face:variable.parameter :foreground ,jetbrains-orange :weight normal)
           (web-mode-builtin-face :inherit font-lock-builtin-face)
           (web-mode-comment-face :inherit font-lock-comment-face)
           (web-mode-css-property-name-face :foreground ,jetbrains-orange)
           (web-mode-function-name-face :foreground ,jetbrains-purple)
           (web-mode-html-attr-name-face :foreground ,jetbrains-gold)
           (web-mode-html-attr-value-face :foreground ,jetbrains-yellow)
           (web-mode-html-tag-face :foreground ,jetbrains-pink :weight bold)
           (web-mode-keyword-face :inherit font-lock-keyword-face)
           (web-mode-string-face :inherit font-lock-string-face)
           (orderless-match-face-0 :foreground ,jetbrains-green :weight bold)
           (orderless-match-face-1 :foreground ,jetbrains-pink :weight bold)
           (orderless-match-face-2 :foreground ,jetbrains-yellow :weight bold)
           (orderless-match-face-3 :foreground ,jetbrains-cyan :weight bold)
           (vertico-current :background ,jetbrains-region :foreground ,jetbrains-fg)
           (vertico-group-title :foreground ,jetbrains-blue :slant italic)
           (vertico-group-separator :foreground ,jetbrains-comment :strike-through t)
           (vertico-quick1 :background ,jetbrains-green :foreground ,jetbrains-bg :weight bold)
           (vertico-quick2 :background ,jetbrains-pink :foreground ,jetbrains-bg :weight bold)
           (marginalia-documentation :foreground ,jetbrains-comment-alt :slant italic)
           (marginalia-file-name :foreground ,jetbrains-comment)
           (marginalia-function :foreground ,jetbrains-purple)
           (marginalia-key :foreground ,jetbrains-blue :weight bold)
           (marginalia-mode :foreground ,jetbrains-gold)
           (marginalia-modified :foreground ,jetbrains-orange)
           (marginalia-number :foreground ,jetbrains-red)
           (marginalia-size :foreground ,jetbrains-teal)
           (marginalia-string :foreground ,jetbrains-yellow)
           (marginalia-symbol :foreground ,jetbrains-blue)
           (marginalia-type :foreground ,jetbrains-gold)
           (marginalia-value :foreground ,jetbrains-comment)
           (which-func :foreground ,jetbrains-purple)
           (which-key-key-face :foreground ,jetbrains-blue)
           (which-key-command-description-face :foreground ,jetbrains-fg)
           (whitespace-empty :background ,jetbrains-maroon :foreground ,jetbrains-red)
           (whitespace-hspace :background ,jetbrains-bg :foreground ,jetbrains-comment)
           (whitespace-indentation :background ,jetbrains-bg :foreground ,jetbrains-orange)
           (whitespace-line :background ,jetbrains-current :foreground ,jetbrains-orange)
           (whitespace-newline :foreground ,jetbrains-comment)
           (whitespace-space :background ,jetbrains-bg :foreground ,jetbrains-comment)
           (whitespace-tab :background ,jetbrains-bg :foreground ,jetbrains-comment))))
    (apply #'custom-theme-set-faces
           'usgc-jetbrains
           (let ((expand-with-func
                  (lambda (func spec)
                    (let (reduced-color-list)
                      (dolist (col colors reduced-color-list)
                        (push (list (car col) (funcall func col))
                              reduced-color-list))
                      (eval `(let ,reduced-color-list
                               (backquote ,spec))))))
                 whole-theme)
             (pcase-dolist (`(,face . ,spec) faces)
               (push `(,face
                       ((((min-colors 16777216)) ,(funcall expand-with-func 'cadr spec))
                        (((min-colors 256)) ,(funcall expand-with-func 'caddr spec))
                        (t ,(funcall expand-with-func 'cadddr spec))))
                     whole-theme))
             whole-theme))))

(provide-theme 'usgc-jetbrains)

;;; usgc-jetbrains-theme.el ends here
